# This is a basic workflow to help you get started with Actions

name: Flutter CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter format .
      
      - run: flutter build apk
      
      - uses: actions/upload-artifact@v2
        with:
            name: flutter-projects
            path: build/app/outputs/apk/release/flutter-projects.apk
      
